Health-Education-England/tis-revalidation-recommendation

- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/Snapshot.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceTest.java
- integration-tests/src/test/java/uk/nhs/hee/tis/revalidation/it/RecommendationIT.java
"Human thought changes:"
- Put more correct Javadocs in place of single line comments
- Added `buildTraineeRecommendationRecordDto()` for common object creation
- Replaced redundant `ClassQualified.references` with normal `references`
- Added `TODO`s for planned changes (I'd like comments now)
"IDE-driven changes"
- Formatting now applied in RecommendationServiceImpl.java
- Replaced deprecated `anyObject()` test
- Removed unused variables and implementation code style
- Fixed 'typoos'
NO-TICKET: Just chores
> Applying docs and code best practices.

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcClientService.java
TIS21-2355: Refresh the Recommendations list frequently
> chore: fix code smell and apply formatting

- application/pom.xml
- application/src/main/java/uk/nhs/hee/tis/revalidation/RevalidationApplication.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/config/SchedulingConfig.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcClientService.java
- application/src/main/resources/application.yml
- application/src/test/java/uk/nhs/hee/tis/revalidation/config/SchedulingConfigTest.java
- pom.xml
There is the expectation that the schedule will be the same across tasks
Any one of the tasks should be capable of running the job as configured
TIS21-2355: Refresh the Recommendations list frequently
> fix: only run a scheduled job in one running task

- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RecommendationStatusCheckUpdatedMessageHandler.java
Objective: - synchronize recommendation/doctor statuses for all cases (not just approved/rejected)
> fix: update all statuses on hourly check

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
> fix: remove ON_HOLD recommendation in UNDER_NOTICE tab

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBController.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBControllerTest.java
> fix: sort doctors summary page by ascending order

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
> fix: add doctors secondary sort by lastname asc

- .github/workflows/deploy.yml
- .github/workflows/pr-analysis.yml
> chore: rename master to main

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/AdminController.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/AdminControllerTest.java
> feat: add gmc nightly sync endpoint

- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/AdminControllerTest.java
TIS21-2484: Manually trigger job, for when it fails
> chore: resolve access modifier code smell

- application/src/main/java/uk/nhs/hee/tis/revalidation/changelog/RemoveInvalidRecommendationsFor6167961ChangeLog.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/changelog/RemoveInvalidRecommendationsFor6167961ChangeLogTest.java
TICKET-TIS21-2650: Recommendations - no make recommendation button for a doctor Under Notice
> fix: remove invalid recommendation and snapshot for doctor 6167961

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceTest.java
TIS21-2631: Recommendation Feedback: Actual Submission Date/GMC Submission Due date in Doctor's details not sorting in the right order
> fix: sort doctor recommendations by date descending

- application/src/main/resources/application.yml
and fix midnight corn to start at mid-night instead of hourly
<NO-TICKET>
> chore: update hourly corn to start at 8am, 12noon, 4pm per day

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
> fix: prevent sending of null gmc recommendation ids for status check

- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/RevalidationSummaryDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/DoctorsForDB.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/payloads/IndexSyncMessage.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncServiceTest.java
- integration-tests/src/test/java/uk/nhs/hee/tis/revalidation/it/BaseIT.java
> chore: add fields to reval es rebuild job

- .aws/task-definition-prod.json
- .aws/task-definition.json
- application/pom.xml
- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/MasterDoctorViewDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/MasterDoctorView.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/RecommendationView.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/ElasticSearchIndexMapper.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/receiver/EsRebuildMessageReceiver.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/receiver/MessageReceiver.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/ElasticSearchIndexUpdateHelper.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/MasterElasticSearchService.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationElasticSearchService.java
- application/src/main/resources/application.yml
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListenerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/receiver/EsRebuildMessageReceiverTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/ElasticSearchIndexUpdateHelperTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationElasticSearchServiceTest.java
- listen to queue `reval.queue.indexrebuildgetmastercommand.requested.recommendation`
- Elastic search set up
- delete and recreate Recommendation Index
- Read trainee information from Master Index
- Map and populate trainee information into Recommendation Index
> feat: ES Recommendation Index

- application/pom.xml
attempt to fix ES version problem when deploy
> chore: update elastic search version

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncServiceTest.java
> fix: map admin fields for ES rebuild job

- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
> chore add Scheduler Lock for index rebuild get master job

- README.md
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/DoctorsForDB.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/DoctorsForDBRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
- integration-tests/src/test/java/uk/nhs/hee/tis/revalidation/it/BaseIT.java
TIS21-2838: Change hide doctor functionality to use boolean flag instead of dbc prefix
> fix: hide doctors with flag instead of modifying dbc

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorConnectionSyncServiceTest.java
> fix: ES rebuild job map `admin` field from DoctorsForDB

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcClientService.java
> chore: improve logging for chekcRecommendationStatus catch statement

- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/MasterDoctorView.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/RecommendationView.java
> fix: add missing existsInGmc field to ES views

- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListenerTest.java
TIS21-2873: [Filter Recommendations with ES] - Event Handling Job For Data Changes (TIS)
> fix: discard null masterdoctorviews with null gmc numbers

- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/TraineeInfoDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/RecommendationView.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/RecommendationViewMapper.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationElasticSearchService.java
- application/src/main/resources/esjson/findAllUnderNotice.json
- application/src/main/resources/esjson/findall.json
- application/src/main/resources/esjson/readme
- application/src/main/resources/esjson/readme.md
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationElasticSearchServiceTest.java
TIS21-276: Filter Recommendations with ES - Retrieve data from ES
> feat: Retrieve all doctors from Elasticsearch,

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceTest.java
TIS21-2826 Actual submission date update for some doctors' in draft
> fix: AcualSubmissionDate should not set for draft

- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/TraineeInfoDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/RecommendationViewMapper.java
TIS21-2675: Filter Recommendations with ES - Retrieve data from ES w/Programme Name filtering
> fix: add missing fields to traineeinfoDto

- application/src/main/java/uk/nhs/hee/tis/revalidation/RevalidationApplication.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/DoctorsForDBRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/validator/TraineeRecommendationRecordDTOValidator.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/RecommendationControllerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/GmcClientServiceTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/validator/TraineeRecommendationRecordDTOValidatorTest.java
> fix: add validation getting value from the backend

- application/src/main/java/uk/nhs/hee/tis/revalidation/changelog/RemoveOrphanedDraftFor7523122.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/changelog/RemoveOrphanedDraftFor7523122ChangeLog.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/changelog/RemoveOrphanedDraftFor7523122ChangeLogTest.java
TIS21-3528 Deletion of doctor's draft recommendation (GMC7523122) in reval under notice
> fix: remove orphaned draft recommendation

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBController.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/TraineeRequestDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/resources/esjson/findAllUnderNotice.json
- application/src/main/resources/esjson/findall.json
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBControllerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-3554: Change existing query in ES to include GMC status as separate parameters
> feat: implement filter by gmc status/outcome

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBController.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/TraineeRequestDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/resources/esjson/findAllUnderNotice.json
- application/src/main/resources/esjson/findall.json
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBControllerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-3604: Change existing query in ES to include TIS status as separate parameters
> feat: filter doctors by tis status

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBController.java
> chore: remove unused inports in DoctorsForDBController

- application/src/main/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBController.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/TraineeRequestDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/resources/esjson/findAllUnderNotice.json
- application/src/main/resources/esjson/findall.json
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/DoctorsForDBControllerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-3741: Update existing query in ES to include TIS admin as separate parameters
> feat: add search recommendations by admin

- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/RecommendationElasticSearchRepository.java
It hurts a little to not do anything to prevent reoccurance,
but this seemed important to highlight where I think the issue is.
TIS21-3741: Filter by TIS admin
> fix: include opening bracket for filter array

- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
> chore: enable logging for overnight doctor syn job received doctors

- application/src/main/java/uk/nhs/hee/tis/revalidation/entity/GmcResponseCode.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/controller/RecommendationControllerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceTest.java
- added the new gmc response code 161
- added a test to check if that message is passed through
> feat: add new gmc response code TIS21-3583

- application/src/main/java/uk/nhs/hee/tis/revalidation/config/RabbitConfig.java
TIS21-3846: Recommendation List missing doctors
> fix: remove conflicting declaration of queue

- application/src/main/java/uk/nhs/hee/tis/revalidation/changelog/RemoveDuplicateDraftsFor7496627ChangeLog.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/changelog/RemoveDuplicateDraftsFor7496627ChangeLogTest.java
> fix: remove duplicate drafts for 7496627 with mongock

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
> feat:set DBC to Null when nightly GMC Sync starts

- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/ConnectionMessageDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListenerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-5015: Update submission date using gmc tryadddoctor response data when connecting a doctor
> fix: update submission date when adding a new connection

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-5017: Set lastupdatedDate when add/remove a connection
> fix: set last updated date when adding or removing connection

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
TIS21-5014: Set underNotice to NO when disconnecting a doctor
> fix: set under notice to no when disconnecting a doctor

- application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/DoctorsForDbMapper.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/mapper/DoctorForDbMapperTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
Custom mapping made it harder to spot a NPE.
chore: cleaning up code smells
TIS21-5296: Doctors not appearing in Connections
> fix: use mapstruct for conversion

- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceTest.java
There are existing code smells which I will only get to after this PR.  It is important that changes are released today to minimise the duration of a problem getting information from the GMC.
TIS21-5296: Doctors not appearing in Connections
> fix: NPE on underNotice check

- application/src/main/java/uk/nhs/hee/tis/revalidation/dto/ConnectionMessageDto.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListenerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
depends on https://github.com/Health-Education-England/tis-revalidation-connection/pull/244
TIS21-5224
> feat:update gmcUpdatedDateTime when connect/disconnect doctor

- application/src/main/java/uk/nhs/hee/tis/revalidation/changelog/RemoveDuplicateDraftFor7409676ChangeLog.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/changelog/RemoveDuplicateDraftFor7409676ChangeLogTest.java
> fix: remove duplicate draft for 7409676

- .github/workflows/deploy.yml
- .github/workflows/pr-analysis.yml
- application/src/main/java/uk/nhs/hee/tis/revalidation/event/DoctorsForDbCollectedEvent.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/DoctorsForDbMapper.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/repository/DoctorsForDBRepository.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
- application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorNightlySyncService.java
- application/src/main/resources/application.yml
- application/src/test/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListenerTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBServiceTest.java
- application/src/test/java/uk/nhs/hee/tis/revalidation/service/GmcDoctorNightlySyncServiceTest.java
- integration-tests/src/test/java/uk/nhs/hee/tis/revalidation/it/ConcurrentDisconnectsIntTest.java
- pom.xml
WIP: Need some comments. This has been implemented based @CaiWillis 's suggestions in the Slack discussions thread.
> feat: handle disconnection doctors

- README.md
- integration-tests/src/test/resources/application-test.yml
docs: update description of the sync jobs
TIS21-5226: Disconnect Doctors
> chore: remove unused app property

- .aws/task-definition-prod.json
- .aws/task-definition.json
- application/src/main/resources/application.yml
TIS21-6612: Upgrade Reval DocDB Cluster
> chore: use parameter store value for mongo connection string parameters

- .github/workflows/deploy.yml
> chore: update GHA -artifact step versions to v4
